# Generated by Django 3.2.5 on 2021-07-21 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amazon_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('ebay_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('amazon_url', models.URLField()),
                ('amazon_asin', models.CharField(max_length=12, unique=True)),
                ('ebay_url', models.URLField()),
                ('image_url', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='products/')),
                ('thumb', models.ImageField(blank=True, default=None, null=True, upload_to='thumbs/')),
            ],
        ),
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='My List', max_length=50)),
                ('products', models.ManyToManyField(blank=True, related_name='savedproducts', to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikeButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ManyToManyField(blank=True, related_name='likebutton', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
