# Generated by Django 3.2.5 on 2021-07-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210722_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumb',
        ),
        migrations.AddField(
            model_name='product',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=1, default=-1, max_digits=2),
        ),
    ]
