# Generated by Django 3.2.5 on 2021-07-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210724_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amazon_asin',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
