# Generated by Django 3.2.5 on 2021-07-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_amazon_asin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='image_location',
        ),
    ]
