# Generated by Django 3.2.5 on 2021-07-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_image_url_product_image_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_location',
            new_name='image_url',
        ),
    ]
